networks:
  ohshift:

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sleep infinity
    env_file:
      - .env
      # - .env.secret
    volumes:
      - ..:/workspace:cached
    networks:
      - ohshift
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - psql-data:/tmp/dev/pgsql/data
    env_file:
        - .env
    expose:
      - "5432"
    ports:
      - "55432:5432"
    networks:
      - ohshift

volumes:
  psql-data:
