ARG VARIANT=bullseye
ARG GO_VERSION=1.24

FROM --platform=linux/amd64 mcr.microsoft.com/vscode/devcontainers/go:${GO_VERSION}-${VARIANT}

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor > /usr/share/keyrings/yarn-archive-keyring.gpg

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    bash-completion uuid-runtime iputils-ping zsh \
    apt-transport-https gnupg lsb-release \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

USER vscode

RUN go install -v github.com/cweill/gotests/gotests@v1.6.0 && \
    go install golang.org/x/vuln/cmd/govulncheck@latest && \
    go install mvdan.cc/gofumpt@latest

WORKDIR /workspace